# Site settings
title: Rackspace Container Service
description: >
  Rackspace-backed containers as a service, making development,
  testing, and deployment of Docker-powered applications hassle-free.

baseurl: "" # the subpath of your site, e.g. /blog/
# Build settings
markdown: redcarpet

redcarpet:
  extensions: ["with_toc_data"]

exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - package.json

permalink: /blog/:title/

collections:
  best-practices:
    output: true
    permalink: /docs/best-practices/:title/
    label: best-practices
  getting-started:
    output: true
    permalink: /docs/getting-started/:title/
    label: getting-started
  tutorials:
    output: true
    permalink: /docs/tutorials/:title/
    label: tutorials



defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "plain"

assets:
  sources:
  - _assets/img
