# Site settings
title: Rackspace Container Service
description: >
  Rackspace-backed containers as a service, making development,
  testing, and deployment of Docker-powered applications hassle-free.

baseurl: "" # the subpath of your site, e.g. /blog/
# Build settings
markdown: redcarpet

exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - package.json

collections:
  tutorials:
    output: true
    permalink: /docs/tutorials/:title/
  best-practices:
    output: true
    permalink: /docs/best-practices/:title/
  references:
    output: true
    permalink: /docs/reference/:title/

defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "page"
